version: '2.2'
services:
  teleport-server:
    image: teleport:1.0
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "443:3080"
    volumes:
      - $PWD/config/teleport.yaml:/etc/teleport/teleport.yaml
      - $PWD/data:/var/lib/teleport
    healthcheck:
      test: tctl status
      interval: 2s
      timeout: 2s
      retries: 3
